### ISSUE TITLE
fromZero works fine for the line, but not for the points

### ISSUE THREAD

**Issue by Bar-Maz** [indiespirit/react-native-chart-kit#125]
After adding fromZero to the LineChart props, line behaves like it should, but datapoints are rendered as if the bottom line was still equal to the minimal value.
![chart](https://user-images.githubusercontent.com/37315072/60181573-c8ff5f00-9822-11e9-9b89-f599395239fe.png)

**Comment by bhoomika911** [comment]
I have the same issue. Any one can help on this?

**Comment by bhoomika911** [comment]
Hi @Bar-Marz,

I was facing same issue.

![image](https://user-images.githubusercontent.com/26411261/60394939-80f57a80-9b49-11e9-8591-b22ef3251c60.png)

To resolve this, I have updated code in **node_modules/react-native-chart-kit/src/line-chart.js** in **renderDots** function as below:

Replace below line

**const cy = (height / 4) *  3 * (1 - (x - Math.min(...datas)) / this.calcScaler(datas)) + paddingTop**

with 

**const cy =
        (baseHeight -  this.calcHeight(x, datas, height)) / 4 * 3 + paddingTop**
          
Result : 

![image](https://user-images.githubusercontent.com/26411261/60394985-0711c100-9b4a-11e9-8fee-f5cc3ee3179f.png)

**Comment by shariqahmed1** [comment]
@bhoomika911 What's the baseHeight?

**Comment by kimspiess** [comment]
I created a pull request to fix this issue as suggested by @bhoomika911

**Comment by Hermanya** [comment]
This is fixed in v3.3.1

**Comment by LaszloLango** [comment]
I've update to the latest (v3.3.1), but I still have the issue. The dots are totally off. Any idea?
